# Ports collection makefile for:	pgdbf
# Date created:				23 June 2009
# Whom:					kirk@daycos.com
#
# $FreeBSD$
#

PORTNAME=	pgdbf
PORTVERSION=	0.5.0
CATEGORIES=	databases
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE}
MASTER_SITE_SUBDIR=	${PORTNAME}

MAINTAINER=	kirk@daycos.com
COMMENT=	Convert XBase / FoxPro tables to PostgreSQL

USE_GMAKE=	yes
GNU_CONFIGURE=	yes

MAN1=		pgdbf.1

PLIST_FILES=	bin/pgdbf \
		share/doc/pgdbf/README

.include <bsd.port.mk>
